source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml
bin.excludes = pom.xml,\
               dbeaver.target,\
               .classpath,\
               .project,\
               .settings/
